name: Publish NuGet package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Extract version from .csproj
      id: version
      run: |
        VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ./src/Nora.Core.Database/Nora.Core.Database.csproj)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create and push tag
      if: env.VERSION != '0.0.0'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag $VERSION
        git push origin $VERSION

    - name: Restore dependencies
      run: dotnet restore ./src/Nora.Core.Database/Nora.Core.Database.csproj

    - name: Build
      run: dotnet build ./src/Nora.Core.Database/Nora.Core.Database.csproj --configuration Release --no-restore

    - name: Pack with tag-based version
      run: dotnet pack ./src/Nora.Core.Database/Nora.Core.Database.csproj --configuration Release --no-build /p:PackageVersion=${{ env.VERSION }}

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./src/Nora.Core.Database/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/wjnnora/index.json" --api-key ${{ secrets.GH_PACKAGES_PAT }}